project_name: "{{ .GithubProject }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./bin/build-completions.sh {{`{{ .ProjectName }}`}}
    - ./bin/build-manpages.sh {{`{{ .ProjectName }}`}}
    - ./bin/build-schema.sh {{`{{ .ProjectName }}`}}

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    # `flags`, `ldflags`, and `mod_timestamp` are configured for reproducible builds.
    # See: https://goreleaser.com/customization/builds/#reproducible-builds
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{`{{.Version}}`}} -X main.commit={{`{{.Commit}}`}} -X main.date={{`{{.CommitDate}}`}}
    mod_timestamp: "{{`{{ .CommitTimestamp }}`}}"

archives:
  - id: default
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - src: build/completions/*
        dst: completions
        strip_parent: true
      - src: build/manpages/*
        dst: manpages
        strip_parent: true
      - src: build/schemas/*
        dst: schemas
        strip_parent: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    rlcp: true

brews:
  - tap:
      owner: "{{ .GithubUsername }}"
      name: homebrew-tap
      branch: main
    folder: Formula
    homepage: "https://github.com/{{ .GithubUsername }}/{{ .GithubProject }}"
    description: ""
    license: "MIT"
    install: |-
      bin.install "{{ .GithubProject }}"
      bash_completion.install "completions/{{ .GithubProject }}.bash" => "{{ .GithubProject }}"
      zsh_completion.install "completions/{{ .GithubProject }}.zsh" => "_{{ .GithubProject }}"
      fish_completion.install "completions/{{ .GithubProject }}.fish"
      man1.install "manpages/{{ .GithubProject }}.1.gz"
    test: |
      system "#{bin}/{{ .GithubProject }} --version"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

gomod:
  proxy: true

report_sizes: true

snapshot:
  name_template: "{{`{{ incpatch .Version }}`}}-next" # cspell: disable-line

changelog:
  use: github
  sort: asc
  groups:
    - title: New features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 99
