---
excludes:
  - build/**
  - dist/**
  - .cspellcache
output:
  show_context: true
  show_url: true
  syntax_highlight: true
processors:
  - preset: cspell
  - preset: gitleaks
  - preset: markdownlint
  - preset: shellcheck
  - preset: shfmt
