---
output:
  show_context: true
  show_url: true
  syntax_highlight: true
processors:
  - preset: cspell
  - preset: gitleaks
  - preset: gofmt
  - preset: golangci-lint
  - preset: hadolint
  - preset: markdownlint
  - preset: shellcheck
  - preset: shfmt
